#!/usr/bin/env python2
import sys
import os
import tempfile
import asyncore
import time
import hashlib
import shutil
import subprocess
import pwd, grp

import mimetypes
import base64
from smtpd import SMTPServer
import smtplib
import email.utils
from email.parser import Parser
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import logging

"""Decodes winmail.dat tnef files from a saved mail file"""

def process_message(filename):
    print 'Processing message %s' % filename
    fd = open(filename, 'rb')
    data = fd.read()
    fd.close()

    parser = Parser()
    message = parser.parsestr(data)

    for idx, payload in enumerate(message.get_payload()):
        if 'application/ms-tnef' in payload['Content-Type']:
            fd = open(os.path.join('winmail.dat'), 'wb')
            fd.write(base64.b64decode(payload.get_payload()))
            fd.close()

            print tnef_list('winmail.dat')
            tnef_extract('winmail.dat')
            os.unlink('winmail.dat')
            break
            
def tnef_list(filename):
    pd = subprocess.Popen('tnef -t "%s"' % (filename,), shell=True, stdout=subprocess.PIPE)
    pd.wait()
    (stdout, stderr) = pd.communicate()
    attachments = []
    for attachment in stdout.strip().split('\n'):
        attachments.append(attachment.split('|')[0].strip())
    return attachments

def tnef_extract(filename):
    pd = subprocess.Popen('tnef %s' % filename, shell=True)
    pd.wait()

if __name__ == '__main__':
    process_message(sys.argv[1])
